# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gateway-server-deployment
serviceName: gateway-server
appLabel: gateway-server
appName: gateway-server


replicaCount: 1

image:
  repository: dockerxya/gateway-server
  tag: latest

containerPort: 8072

service:
  type: LoadBalancer
  port: 8072
  targetPort: 8072

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
k8s_discovery_enabled: true
keycloak_enabled: true
resouceserver_enabled: true
otel_enabled: true
kafka_enabled: false
rabbitmq_enabled: false
appname_enabled: true
mysqldb_used: false