# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: bank-messaging-service-deployment
serviceName: bank-messaging-service
appLabel: bank-messaging-service
appName: bank-messaging-service

replicaCount: 1

image:
  repository: dockerxya/bank-messaging-service
  tag: latest

containerPort: 9010

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
k8s_discovery_enabled: false
zipkin_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: true
rabbitmq_enabled: true
mysqldb_used: false